### ISSUE TITLE
Model Spec: Review and Incorporate Feedback

### ISSUE THREAD

**Issue by andymithamclarke** [urbanbigdatacentre/ideamaps-models#10]
We need to incorporate changes as a result of the feedback given in the full team meeting on the model spec.

We also need to send an email to city liasons with the ability to provide comments and suggestions on the model spec.

This issue can be closed once all comments have been considered and the document has reached a final 'workable' condition.

**Comment by andymithamclarke** [comment]
This document should be shared with Bunmi - Mary - Taiwo ... unless otherwise specified.

**Comment by andymithamclarke** [comment]
Friday 22nd - Circulated to WP2/3
Tuesday 26th - Circulated to City Liasons
Wednesday 27th - IDEAMAPS Team Meeting
Wed 27th - Wed 3rd - @Gtregon to review and incorporate feedback

🚨 FINAL VERSION - Friday 5th 🚨

**Comment by andymithamclarke** [comment]
@Gtregon - paste link to document here plz

**Comment by andymithamclarke** [comment]
@gielinkg - Ask Mary to join the team meeting.

Plan B is to find a time to meet with her before the end of the week

Plan C is to send her the document and then ask for review - then looping her feedback in later down the line.

**Comment by andymithamclarke** [comment]
**Updated Dates**

Friday 22nd - Circulated to WP2/3
Wednesday 27th - IDEAMAPS Team Meeting
Thursday 28th - Circulated to City Liasons - PLAN C - with targetted questions
5th April - deadline for comments
12th April - @Gtregon deadline for incorporation

🚨 FINAL VERSION - Friday 12th April 🚨

**Comment by Gtregon** [comment]
Deadline changed to 19th April as WP2/3 team had additional feedback. This will be finalised by Friday19th April.

**Comment by andymithamclarke** [comment]
@Gtregon  to send out on Friday

**Comment by Gtregon** [comment]
UPDATE

Full team draft sent on Friday 19th.
Team meeting feedback on 24th.

**Comment by Gtregon** [comment]
Draft sent to full team on 24th by Grant
