### ISSUE TITLE
Create the new rule based methodology based on the new High/medium/low reference categories

### ISSUE THREAD

**Issue by qszhao** [urbanbigdatacentre/ideamaps-models#102]
This will based on the discuss on 17 and 18 Sep from backlog meeting and WP2/3 meeting.

**Comment by qszhao** [comment]
We will need to test which road metrics will be the most useful for generating the categories.

**Comment by qszhao** [comment]
This will be done with Sebastian's support.

**Comment by diegopajarito** [comment]
@SebastianHafner has proposed a new method that includes post-processing. This needs to be reviewed by @qszhao & @joaoporto 

Once this is approved @SebastianHafner will update/close the issue.

**Comment by gielinkg** [comment]
Has been reviewed and approved by Joao. 
The model proposed by Sebastian and Manuella was agreed.
