### ISSUE TITLE
Create New Reference Dataset with high/medium/low categories

### ISSUE THREAD

**Issue by qszhao** [urbanbigdatacentre/ideamaps-models#103]
We will finalise the validation datasets: 
1. Adenike/Alex’s human-generated training datasets - only for Lagos, very limited for Kano. We need to find out where are the source for Monika's Nairobi data. 
2. PAR data validation for SDS/ISL/overall deprivation. We will need to create this data based on the PAR results and combine it with the master datasets @manuellacomerio will create.

**Comment by andymithamclarke** [comment]
This is an ongoing process to determine how and whether to use the validation data created by @Adenikemie and @AlexandraMiddleton  as part of the creation of new training data.

Progress so far is that a meeting was held with the above + @manuellacomerio - outcome: reporting to @qszhao all of the workflows that they have done.

Next steps - a subsequent meeting to determine information about the grid that was used and to see whether the grid matches.

**Comment by qszhao** [comment]
@manuellacomerio will convert the SDS/ISL output grid for Lagos and Kano from the output files and try to match it with Adenike/Alex's validation data. If the grid matches, the data will be joined. She will also try to match it with Nairobi data Monika supplied. 

Then PAR data will be joined to the grid. @andymithamclarke if you can help @manuellacomerio to identify the PAR results that will be great. Now it is a bit confused which one we should use.

**Comment by andymithamclarke** [comment]
Closing this as complete - see update in #101

**Comment by qszhao** [comment]
Reopen the issue - we will need to generate the new high/medium/low categories for morphological informality based on the reference data in Nairobi and Lagos, plus the PAR results for SDS and ISL.

**Comment by diegopajarito** [comment]
Reference dataset with L/M/H is ready for Nairobi. This has been shared over CRIB and GDrive. 

Reference dataset with L/M/H are planned for Next Friday. @SebastianHafner @manuellacomerio will update on the progress

**Comment by gielinkg** [comment]
@SebastianHafner to upload reference to GDrive and CRIB for Lagos. @SebastianHafner to close this issue once all the data is uploaded to the appropriate locations.

**Comment by andymithamclarke** [comment]
Closing as archived?
