### ISSUE TITLE
Generate outputs based on the new training datasets and rule-based methods

### ISSUE THREAD

**Issue by qszhao** [urbanbigdatacentre/ideamaps-models#104]
Create outputs from the newly generated rule-based models.

**Comment by andymithamclarke** [comment]
@diegopajarito highlights that this is no longer valid and that we are agreed on going with a rule based approach.

@qszhao confirm and close the issue OR convert this issue into a more appropriate title and description to reflect this decision.

**Comment by andymithamclarke** [comment]
This issue can be closed once the repository folder meets the specifications outlined in the platform documentation @andymithamclarke to link this here.

https://github.com/urbanbigdatacentre/ideamaps-application-backend/tree/development/docs/data

**Comment by andymithamclarke** [comment]
Nairobi definately 
Lagos maybe 

@SebastianHafner to update

**Comment by diegopajarito** [comment]
@SebastianHafner has generated model outputs for Nairobi, they're pending validation described in #102

**Comment by gielinkg** [comment]
Sebastian met with Joao week of 14/10 -- model outputs for Nairobi were agreed.
