### ISSUE TITLE
Revise Laypersons Slides for Co-design Process - Healthcare

### ISSUE THREAD

**Issue by andymithamclarke** [urbanbigdatacentre/ideamaps-models#114]
### ✅ Definition of Done
---

- [ ] 1. Define acceptance criteria.
- [ ] 2. Assess the need for a review process. If a review process is required, the issue states:
    1. Who is involved in the review?
    2. When will the review take place?
    3. Who is responsible for taking on the feedback?
    4. What additional tasks are involved and are they visible on the backlog?
- [ ] 3. Make progress and post updates.
- [ ] 4. Check off completed acceptance criteria.
- [ ] 5. Post links to digital outputs.
- [ ] 6. Note the value added to the product.

**Comment by diegopajarito** [comment]
A new document was shared with an extended domain expert group on Friday

https://docs.google.com/document/d/1lBspWLuTfyq56bfxzOGfa-DfSrFFIYml/edit?usp=sharing&ouid=115390532617165323330&rtpof=true&sd=true

It has improvements on model background, overview, and three-step classification. 

It proposes a classification of HC facilities based on ownership that needs to be validated by domain experts. 

Closed as completed.
