### ISSUE TITLE
WP2/3 Progress for Gates Report

### ISSUE THREAD

**Issue by andymithamclarke** [urbanbigdatacentre/ideamaps-models#127]
### ✅ Definition of Done
---

- [ ] 1. Define acceptance criteria.
- [ ] 2. Assess the need for a review process. If a review process is required, the issue states:
    1. Who is involved in the review?
    2. When will the review take place?
    3. Who is responsible for taking on the feedback?
    4. What additional tasks are involved and are they visible on the backlog?
- [ ] 3. Make progress and post updates.
- [ ] 4. Check off completed acceptance criteria.
- [ ] 5. Post links to digital outputs.
- [ ] 6. Note the value added to the product.

**Comment by diegopajarito** [comment]
A list of items was added to the progress section for phase 2. This is not extensive and might need additional input from other PIs and in-country colleagues. 
Also, two items for the outlook were added. Id suggest the issue to be closed since the technical team had already provided input
