### ISSUE TITLE
PAR Data Analysis - Nairobi + Lagos > Morph Inf.

### ISSUE THREAD

**Issue by andymithamclarke** [urbanbigdatacentre/ideamaps-models#128]
### ✅ Definition of Done
---

- [ ] 1. Define acceptance criteria.
- [ ] 2. Assess the need for a review process. If a review process is required, the issue states:
    1. Who is involved in the review?
    2. When will the review take place?
    3. Who is responsible for taking on the feedback?
    4. What additional tasks are involved and are they visible on the backlog?
- [ ] 3. Make progress and post updates.
- [ ] 4. Check off completed acceptance criteria.
- [ ] 5. Post links to digital outputs.
- [ ] 6. Note the value added to the product.

**Comment by manuellacomerio** [comment]
On-going analysis comparing PAR MI validations against model outputs for Nairobi and Lagos. Will get together with @SebastianHafner by the beginning of next week to get through it.

**Comment by andymithamclarke** [comment]
[like]  Andrew Clarke reacted to your message:
________________________________

**Comment by andymithamclarke** [comment]
Closing with future work planned in Sprint 6
