### ISSUE TITLE
Gates Financial Reporting

### ISSUE THREAD

**Issue by gielinkg** [urbanbigdatacentre/ideamaps-models#129]
### ✅ Definition of Done
---

- [x] 1. Define acceptance criteria.
- [x] 2. Assess the need for a review process. If a review process is required, the issue states:
    1. Who is involved in the review?
    2. When will the review take place?
    3. Who is responsible for taking on the feedback?
    4. What additional tasks are involved and are they visible on the backlog?
- [x] 3. Make progress and post updates.
- [ ] 4. Check off completed acceptance criteria.
- [ ] 5. Post links to digital outputs.
- [ ] 6. Note the value added to the product.

**Comment by gielinkg** [comment]
The Research Support Office needs to complete the reporting template for BMFG. 

The full report, including non-financial narrative, is due on November 30th. 

@gielinkg has already completed the summary budget template which includes partner spend amounts and forecasted spend for Year 3. This has been sent to Jonny Houston already and will be shared with RSO to support their template completion. All partner spends are in-line with their budget apart from Lagos, which is reporting an overspend of around 12k USD with existing forecasts for Year 3. 

@joaoporto and @gielinkg have discussed a proposal for a No Cost Extension to the grant for 6 months. This proposal will also be submitted on November 30th with the full progress report. 

**Needs Done:** 
- @gielinkg confirm contact in RSO who will complete the report. 
- @gielinkg complete the salary calculations (discussed on Oct. 31st and inclusive of NCE) to verify expected underspend --> to help determine if we will ask to vire any of this amount to another budget category. 
- @gielinkg complete the forecasts for travel to Nigeria and hosting in Glasgow (plus some partner travel) --> to include in spend plans for Year 3+
- @gielinkg ask for support from RSO in crafting a budget proposal for 6 months NCE. This may require a meeting with @joaoporto and @gielinkg

**Comment by gielinkg** [comment]
Angela has responded with support, I now expect to be in touch with Kris Paisley over the next week to arrange all necessary items on the financial report.

**Comment by andymithamclarke** [comment]
Closing as complete - report submitted 🚀

**Comment by gielinkg** [comment]
Submitted docs here: https://gla.sharepoint.com/:f:/s/IDEAMAPSEcosystem/En3hRUMPsBBKjeTGRAsFFvwBghAjxcMcYk7W_2jHtGNG9Q?e=r2W9pl
