### ISSUE TITLE
Create 1st Draft of Ref Data

### ISSUE THREAD

**Issue by andymithamclarke** [urbanbigdatacentre/ideamaps-models#13]
We need to incorporate the feedback given by the WP2/3 team on the first draft of reference data and the resusability document created in #9 .

Any feedback that is provided should result in action that can be completed within a week.

**Comment by Gtregon** [comment]
This issue can be closed when: The reference data and the documentation will be stored on the shared drive.

**Comment by Gtregon** [comment]
Question to bring to the WP2/3 team: decide where the data will be stored on G drive if not sensitive and if sensitive stored on CRIB.

**Comment by andymithamclarke** [comment]
@Adenikemie can you provide a link to this document here. Additionally - please provide explicitcomment saying that this reusability document is complete.

**Comment by andymithamclarke** [comment]
UPDATE: Splitting task so that reusability document is separate

**Comment by andymithamclarke** [comment]
This is now a standalone dataset and no longer part of any training processes for phase 2.1 - NO BLOCKER
