### ISSUE TITLE
Create draft visualisation / maps of PAR Feedback on Healthcare Access

### ISSUE THREAD

**Issue by diegopajarito** [urbanbigdatacentre/ideamaps-models#133]
To share with the in-country partners, we will prepare maps and plots using the feedback data captured during the PARs in Kano about the healthcare model. 

The idea is that colleagues, modellers and PIs start shaping features that would define the Barriers to Maternal Healthcare Model 

### ✅ Definition of Done
---

- [ ] 1. Define acceptance criteria.
- [ ] 2. Assess the need for a review process. If a review process is required, the issue states:
    1. Who is involved in the review?
    2. When will the review take place?
    3. Who is responsible for taking on the feedback?
    4. What additional tasks are involved and are they visible on the backlog?
- [ ] 3. Make progress and post updates.
- [ ] 4. Check off completed acceptance criteria.
- [ ] 5. Post links to digital outputs.
- [ ] 6. Note the value added to the product.

**Comment by andymithamclarke** [comment]
Closing as archived
