### ISSUE TITLE
PAR Presentation of Results - LAGOS

### ISSUE THREAD

**Issue by andymithamclarke** [urbanbigdatacentre/ideamaps-models#145]
### ✅ Definition of Done
---

- [ ] 1. Define acceptance criteria.
- [ ] 2. Assess the need for a review process. If a review process is required, the issue states:
    1. Who is involved in the review?
    2. When will the review take place?
    3. Who is responsible for taking on the feedback?
    4. What additional tasks are involved and are they visible on the backlog?
- [ ] 3. Make progress and post updates.
- [ ] 4. Check off completed acceptance criteria.
- [ ] 5. Post links to digital outputs.
- [ ] 6. Note the value added to the product.

**Comment by andymithamclarke** [comment]
This involves 

"specifically improving the quality of the basemaps (Use Mapbox where possible) + colors used for Low - Medium - High (Same as Interface)"

**Comment by manuellacomerio** [comment]
Colour scheme has been updated for graphs, still working on the basemap improvement with support from @andymithamclarke

**Comment by andymithamclarke** [comment]
Closing as complete - all work to improve presentation inc basemaps and colors concluded - resources available here 


https://gla.sharepoint.com/sites/IDEAMAPSEcosystem/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FIDEAMAPSEcosystem%2FShared%20Documents%2FGeneral%2FProject%20Admin%2FMeeting%20Minutes%2FLagos%20and%20Kano%20Working%20Group%20Meeting%20Minutes%20and%20Docs%2F09%20December%202024&p=true&ga=1
