### ISSUE TITLE
PAR Presentation of Results - NAIROBI (Improve Only ** )

### ISSUE THREAD

**Issue by andymithamclarke** [urbanbigdatacentre/ideamaps-models#147]
### ✅ Definition of Done
---

- [ ] 1. Define acceptance criteria.
- [ ] 2. Assess the need for a review process. If a review process is required, the issue states:
    1. Who is involved in the review?
    2. When will the review take place?
    3. Who is responsible for taking on the feedback?
    4. What additional tasks are involved and are they visible on the backlog?
- [ ] 3. Make progress and post updates.
- [ ] 4. Check off completed acceptance criteria.
- [ ] 5. Post links to digital outputs.
- [ ] 6. Note the value added to the product.

**Comment by gielinkg** [comment]
Nairobi Priorities Report Document: https://docs.google.com/document/d/1Z572cOaGs98A5eTXnVyqIQtJzleb1t72Mp4MyF_RUYc/edit?usp=sharing

**Comment by manuellacomerio** [comment]
Colour scheme has been updated for graphs, still working on the basemap improvement with support from @andymithamclarke

**Comment by andymithamclarke** [comment]
Closing as complete - comments above satisfied and presentation updated  here -  https://gla.sharepoint.com/:p:/r/sites/IDEAMAPSEcosystem/_layouts/15/Doc.aspx?sourcedoc=%7B11E5673E-A04B-4419-BA64-6CFCB16C8B9A%7D&file=Nairobi%20-%20PAR%20Results%20Analysis%20%E2%80%93%20Morphological%20Informality.pptx&action=edit&mobileredirect=true
