### ISSUE TITLE
Full Team Meeting

### ISSUE THREAD

**Issue by gielinkg** [urbanbigdatacentre/ideamaps-models#149]

**Comment by andymithamclarke** [comment]
Menti Presentation to use for Data Summary Co-design

https://www.menti.com/alqvg574f97b

**Comment by andymithamclarke** [comment]
Attached is co-design results @gielinkg @joaoporto 

[RESULTS Data Summaries Co-design.pdf](https://github.com/user-attachments/files/18153134/RESULTS.Data.Summaries.Co-design.pdf)

**Comment by gielinkg** [comment]
@andymithamclarke  great thanks these have now been uploaded to the folder for yesterday's meeting: https://gla.sharepoint.com/:f:/s/IDEAMAPSEcosystem/Eh4vm7l-zSNEqDNDrJSkKAEBG6CzAsqGrusEZXWiNhYMzQ?e=qnEgvF
