### ISSUE TITLE
Running of morphological informality model - NAIROBI ONLY

### ISSUE THREAD

**Issue by Gtregon** [urbanbigdatacentre/ideamaps-models#18]
The source code developed in #14 will be used to run a random forest model using reference data developed during #15 #16 #17 and Sentinel-2 imagery to generate three classes of morphological informality (high, med and low). Supplementary data will also be used to conduct an accuracy assessment of model outputs e.g. 80% of reference/satellite data will be ingested within the RF model, whilst 20% will be used to validate/assess accuracy of model outputs.

This issue can be closed when the model has been ran for all three pilot cities and outputs have been uploaded to the github repo

**Comment by andymithamclarke** [comment]
UPDATE NAIROBI ONLY

**Comment by gielinkg** [comment]
✅ Definition of Done

- [ ] 1. Define acceptance criteria.
- [ ]  2. Assess the need for a review process. If a review process is required, the issue states:
i. Who is involved in the review?
ii. When will the review take place?
iii.  Who is responsible for taking on the feedback?
iv. What additional tasks are involved and are they visible on the backlog?
 - [ ] 3. Make progress and post updates.
- [ ]  4. Check off completed acceptance criteria.
- [ ]  5. Post links to digital outputs.
- [ ]  6. Note the value added to the product.

**Comment by gielinkg** [comment]
Closing this because we have combined with the writing of the source code, see issue #14
