### ISSUE TITLE
Accuracy assessment of model outputs

### ISSUE THREAD

**Issue by Gtregon** [urbanbigdatacentre/ideamaps-models#19]
The outputs from the Morphological informality model will be assessed for accuracy using a sample of the reference data generated in #15 #16 #17 .

This issue can be closed once metrics have been developed for the model outputs and circulated to the WP2/3 team.

**Comment by gielinkg** [comment]
✅ Definition of Done

- [ ]  1. Define acceptance criteria.
- [ ]  2. Assess the need for a review process. If a review process is required, the issue states:
i. Who is involved in the review?
ii. When will the review take place?
iii. Who is responsible for taking on the feedback?
iv. What additional tasks are involved and are they visible on the backlog?
- [ ]  3. Make progress and post updates.
- [ ]  4. Check off completed acceptance criteria.
- [ ]  5. Post links to digital outputs.
- [ ]  6. Note the value added to the product.

**Comment by andymithamclarke** [comment]
This is now built into the source code of the model work.
