### ISSUE TITLE
Cleanup old versions of models

### ISSUE THREAD

**Issue by Gtregon** [urbanbigdatacentre/ideamaps-models#2]
Refine scripts used for ISL, SDS and OD i.e. pull out metric scripts used for each model.

This issue can be closed when each sub-domain model has a list of scripts that are explicitly used to model the sub-domain i.e. SDS contains scripts for the 11 metrics used to model SDS etc.

**Comment by andymithamclarke** [comment]
This issue can be closed once all files related to the old model versions exist within the remote github repository under the appropriate folder locations (commit + push)

**Comment by Gtregon** [comment]
UPDATE:

I believe this issue is now redundant, as the framework of the old models will not be used in this phase of the project.

To be discussed during the sprint meeting on 15th April. Issue will be closed once group agrees.
