### ISSUE TITLE
Model spec: FINAL DRAFT

### ISSUE THREAD

**Issue by Gtregon** [urbanbigdatacentre/ideamaps-models#21]
Upload final version on the 26th April

**Comment by Gtregon** [comment]
The parameter thresholds drafted in #20 will be finalised in this document and all other feedback from the team meeting and WP2/3 meeting will be incorporated. These will be used to help define the model inputs (buildings, roads, population etc) in #17 #16 #15.

This issue can be closed when the final draft of the morphological document is complete, with parameter thresholds defined and all feedback has been incorporated.

**Comment by andymithamclarke** [comment]
To complete this task we need:
- Clear understandable definition of how classes will be computed
- Communicable text for the definition of categories
- Examples of the implications of these categories for all pilot cities - should feature parts of the city in high medium low with photos.

**Comment by andymithamclarke** [comment]
@Gtregon there are two documents emerging from this task

1. Lehmans model
2. Technical Doc

This issue can be closed once these documents are complete and links are provided here and the above acceptance criteria

**Comment by gielinkg** [comment]
✅ Definition of Done

- [ ] 1. Define acceptance criteria.
- [ ]  2. Assess the need for a review process. If a review process is required, the issue states:
i. Who is involved in the review?
ii. When will the review take place?
iii.  Who is responsible for taking on the feedback?
iv. What additional tasks are involved and are they visible on the backlog?
 - [ ] 3. Make progress and post updates.
- [ ]  4. Check off completed acceptance criteria.
- [ ]  5. Post links to digital outputs.
- [ ]  6. Note the value added to the product.

**Comment by gielinkg** [comment]
@Gtregon  Can you upload the version that we showed at the co-design meeting?
