### ISSUE TITLE
Migrate Spatial Data from G-Drive to CRIB

### ISSUE THREAD

**Issue by andymithamclarke** [urbanbigdatacentre/ideamaps-models#27]
We need to move the raw data to CRIB. The reason for doing this is to have a single source of truth for all training - reference data (and other) that is used for the modelling. This is a secure location that takes away any need to consider data management plan.

This issue can be closed when we have all spatial data relating to the project has been migrated to CRIB.

**Comment by Gtregon** [comment]
To prioritise migrating the larger datasets

**Comment by gielinkg** [comment]
✅ Definition of Done

- [ ] 1. Define acceptance criteria.
- [ ]  2. Assess the need for a review process. If a review process is required, the issue states:
i. Who is involved in the review?
ii. When will the review take place?
iii.  Who is responsible for taking on the feedback?
iv. What additional tasks are involved and are they visible on the backlog?
 - [ ] 3. Make progress and post updates.
- [ ]  4. Check off completed acceptance criteria.
- [ ]  5. Post links to digital outputs.
- [ ]  6. Note the value added to the product.

**Comment by andymithamclarke** [comment]
No digital ouputs
