### ISSUE TITLE
Begin first silo meeting for sub-domains

### ISSUE THREAD

**Issue by Gtregon** [urbanbigdatacentre/ideamaps-models#28]
The full sub-domain modelling network has met (prev w/c 15th April). Going forward teams will meet within their individual sub-domain groups every two weeks. Between these weeks, the team will also regroup at the WP2/3 meetings (also operating every 2 weeks).

The first meeting will help to define a roadmap for each sub-domain.

Envisaged tasks include:
- define model spec
- define roles and responsibilities within the team
- define model parameters and thresholds
- define datasets associated with model (or activities for data collection/acquisition)
- TBC

**Comment by andymithamclarke** [comment]
@Gtregon provided a template to be filled in by each team 

This issue can be closed once a link to the model specifications for the following models are here in the comments

- WASH - Responsible == Francis
- Housing - Responsible == Toyin
- Health - Responsible == Kenny

The first draft of the model specifications should be ready by Friday 24th May

@Gtregon to decide whether to add specific tasks to the backlog for this work.

**Comment by Gtregon** [comment]
Model owners could not meet last week. Toyin (housing model owner) was able to meet next week. Kenny and Francis (WASH and Healthcare) will be meeting this week with their groups.

**Comment by andymithamclarke** [comment]
@Gtregon to update on this here

**Comment by andymithamclarke** [comment]
Another follow on task?
