### ISSUE TITLE
Stucture Github Repository

### ISSUE THREAD

**Issue by Gtregon** [urbanbigdatacentre/ideamaps-models#3]
Upload the scripts used to model each sub-domain during phase 1 e.g. SDS and the scripts used to model the 11 metrics etc.

**Comment by andymithamclarke** [comment]
We need to create a folder structure for the idemap-models repository. We have a photo of the whiteboard that @Gtregon can use to implement this.

1. Clone the repository to your local machine
2. Design folder hierarchy
3. Add files to appropriate locations
4. Commit and Push the changes

This issue can be closed when one to 4 is reflected in the remote repository.
