### ISSUE TITLE
Review Incorporate Feedback - Model Spec Final

### ISSUE THREAD

**Issue by andymithamclarke** [urbanbigdatacentre/ideamaps-models#32]
We need to review the feedback given on the two model spec documents created in #21 and #31 .

This issue can be closed once the WP2/3 and @qszhao have provided feedback on the document and @Gtregon has incorporated feedback.

**Comment by gielinkg** [comment]
✅ Definition of Done

- [ ] 1. Define acceptance criteria.
- [ ]  2. Assess the need for a review process. If a review process is required, the issue states:
i. Who is involved in the review?
ii. When will the review take place?
iii.  Who is responsible for taking on the feedback?
iv. What additional tasks are involved and are they visible on the backlog?
 - [ ] 3. Make progress and post updates.
- [ ]  4. Check off completed acceptance criteria.
- [ ]  5. Post links to digital outputs.
- [ ]  6. Note the value added to the product.

**Comment by andymithamclarke** [comment]
Closing this issue because document became 2 documents:

- Lehmans
- Technical

Progress on these documents are recorded in #42 #33
