### ISSUE TITLE
Review Lehmans Document - Model Spec (FULL TEAM)

### ISSUE THREAD

**Issue by andymithamclarke** [urbanbigdatacentre/ideamaps-models#33]
We need to bring the lehamns document created in #21 with the full team.

This issue can be closed once a co-design session that reviews the document has been done and the feedback has been recorded.

@Gtregon to provide a summary of the feedback here and a plan of action to incorporate any changes (if appropriate)

**Comment by gielinkg** [comment]
✅ Definition of Done

- [ ] 1. Define acceptance criteria.
- [ ]  2. Assess the need for a review process. If a review process is required, the issue states:
i. Who is involved in the review?
ii. When will the review take place?
iii.  Who is responsible for taking on the feedback?
iv. What additional tasks are involved and are they visible on the backlog?
 - [ ] 3. Make progress and post updates.
- [ ]  4. Check off completed acceptance criteria.
- [ ]  5. Post links to digital outputs.
- [ ]  6. Note the value added to the product.

**Comment by gielinkg** [comment]
Update: We held a co-design session with the team and received helpful feedback, recorded in Menti. We are planning to close issues relating to the "finalisation" of the model spec. @Gtregon will make relevant updates based on last week's feedback, and then we will take an updated version to a meeting with Bunmi, Mansur, and Maryvine, representing each city's governments. The updated model spec will also be included in the June newsletter with a survey reflecting the co-design questions.

**Comment by andymithamclarke** [comment]
We reviewed the document below at the full team meeting - codesign.

![Image](https://github.com/urbanbigdatacentre/ideamaps-models/assets/56840824/945c527a-1827-43a7-a742-3dc910501fe7)

**Comment by andymithamclarke** [comment]
Closing this issue with the mind that the following will happen:


    - Newsletter review is not happening now
    - Meetings with Bunmi, mansur and mary happening soon - feedback will be collected but no further action taken right now
