### ISSUE TITLE
Calculate Road Metrics - NAIROBI ONLY

### ISSUE THREAD

**Issue by andymithamclarke** [urbanbigdatacentre/ideamaps-models#37]
We need to create a model ready dataset for road connectivity for Nairobi.

The starting point of this issue is that two dataset are ready to go within CRIB:

1. OSM Road Data
2. Million Neighbourhood Block Data

**This process will involve:**

Calculate length of internal streets within blocks connected to external st network (m)
Calculate length of internal streets within blocks NOT connected to external st network (m)
This issue can be closed when there is an output dataset that is stored on CRIB and is model ready for NAIROBI.

**Comment by gielinkg** [comment]
✅ Definition of Done

- [ ] 1. Define acceptance criteria.
- [ ]  2. Assess the need for a review process. If a review process is required, the issue states:
i. Who is involved in the review?
ii. When will the review take place?
iii.  Who is responsible for taking on the feedback?
iv. What additional tasks are involved and are they visible on the backlog?
 - [ ] 3. Make progress and post updates.
- [ ]  4. Check off completed acceptance criteria.
- [ ]  5. Post links to digital outputs.
- [ ]  6. Note the value added to the product.
