### ISSUE TITLE
Calculate Population Metrics - NAIROBI Only

### ISSUE THREAD

**Issue by andymithamclarke** [urbanbigdatacentre/ideamaps-models#38]
We need to calculate the model ready population dataset for NAIROBI only. 

The starting point for this issue is the following datasets will be on CRIB.

- GHS Pop 2023

**The process involves creating the following metrics and wrapping them into a model ready dataset**
1. Segment total pop
2. Segment pop density (m/hectare)
3. City total pop
4. City total pop classified as follows
- Less than 250k
- 250-500k
- 500k-1mil
- 1mil - 10mil
- 10milly+ 💰
5. City 2020 - 2025 annual population

This issue can be closed once the dataset representing the above metrics is on CRIB.

**Comment by gielinkg** [comment]
✅ Definition of Done

- [ ] 1. Define acceptance criteria.
- [ ]  2. Assess the need for a review process. If a review process is required, the issue states:
i. Who is involved in the review?
ii. When will the review take place?
iii.  Who is responsible for taking on the feedback?
iv. What additional tasks are involved and are they visible on the backlog?
 - [ ] 3. Make progress and post updates.
- [ ]  4. Check off completed acceptance criteria.
- [ ]  5. Post links to digital outputs.
- [ ]  6. Note the value added to the product.

**Comment by Gtregon** [comment]
No review process needed.

Value added: this will become a key component to the morphological informality model (input variable for assessing high med low MI)
