### ISSUE TITLE
Arrange payment for Vercel and NHost

### ISSUE THREAD

**Issue by gielinkg** [urbanbigdatacentre/ideamaps-models#39]
We need to speak to Yevdokia about paying for the new cloud services via credit card. We need to ask her if there is an option to pay by direct debit. Yevdokia returns from annual leave on May 20th or 21st.

**Comment by gielinkg** [comment]
✅ Definition of Done

- [ ]  1. Define acceptance criteria.
- [ ]  2. Assess the need for a review process. If a review process is required, the issue states:
i. Who is involved in the review?
ii. When will the review take place?
iii. Who is responsible for taking on the feedback?
iv. What additional tasks are involved and are they visible on the backlog?
- [ ]  3. Make progress and post updates.
- [ ]  4. Check off completed acceptance criteria.
- [ ]  5. Post links to digital outputs.
- [ ]  6. Note the value added to the product.

**Comment by gielinkg** [comment]
Yevdokia is now back from AL, I have asked her about whether she could set up a monthly payment for us with her uni credit card.

**Comment by gielinkg** [comment]
@andymithamclarke  Yevdokia responded to us and I forwarded you an email with some brief things for you to confirm before I get back to her. She is going to confirm with Procurement if we can do a direct debit, exceptionally, as it is usually preferred not to do it.

**Comment by andymithamclarke** [comment]
This is great progress 🚀

**Comment by gielinkg** [comment]
I am now liaising further questions with Yevdokia and the Procurement office. Yevdokia is able to pay for the services via CC in the interim. @andymithamclarke  I'll catch up with you on this when you're back. 
We are trying to find the right supplier setup path with respect to the low cost value of these services, as usually supplier setup is for higher values.

**Comment by andymithamclarke** [comment]
Nice one - this is good news. I have time today or tomorrow if that is suitable?

**Comment by gielinkg** [comment]
We'll have an interim CC payment arranged on Friday this week. I am still waiting to hear back from the Procurement Office about officially setting these guys up as suppliers, which hopefully would allow us to have official contracts in place for data storage in the long-term. 

_**The interim payment arrangement will allow us to fully USE the platform, but not store data.**_

We can close this issue on Friday once the payment is complete.

**Comment by andymithamclarke** [comment]
Completed payment with Yevdokia for both providers Nhost + Vercel.

We are on the PRO plan for both providers - Nhost = $25 p/month - Vercel = $20 p/month.

@gielinkg see invoices attached - close the issue when you are satisfied



![Image](https://github.com/urbanbigdatacentre/ideamaps-models/assets/56840824/b62b2a11-24b7-4fdb-beaf-934bcffbd0fc)



![Image](https://github.com/urbanbigdatacentre/ideamaps-models/assets/56840824/567298eb-c4fa-440b-9398-7cfad6f9d225)

**Comment by gielinkg** [comment]
Value added: the issue has allowed us to get the platform up & running, with minimal development effort. With the immediate arrangement of these new services, we have also created a pathway to a more sustainable and cost-saving financial forecast for the platform.
