### ISSUE TITLE
Investigate provider setup requirements with DP/FOI Office

### ISSUE THREAD

**Issue by gielinkg** [urbanbigdatacentre/ideamaps-models#40]
- We need to speak to the data protection and freedom of information office at UofG about the requirements for switching to Vercel/Nhost
- We may need further liaising with the Procurement Office. 
- For now, we are planning to pay for Vercel/Nhost via credit card and we will NOT store any data there until we have approvals in place from the university.

**Comment by gielinkg** [comment]
✅ Definition of Done

- [ ]  1. Define acceptance criteria.
- [ ]  2. Assess the need for a review process. If a review process is required, the issue states:
i. Who is involved in the review?
ii. When will the review take place?
iii. Who is responsible for taking on the feedback?
iv. What additional tasks are involved and are they visible on the backlog?
- [ ]  3. Make progress and post updates.
- [ ]  4. Check off completed acceptance criteria.
- [ ]  5. Post links to digital outputs.
- [ ]  6. Note the value added to the product.

**Comment by gielinkg** [comment]
We got a response from the DP Office, which @diegopajarito has reviewed. We believe the first step is to draft an amendment to the Ethics App which includes the DPIA. @diegopajarito is going to prioritise this step now.

**Comment by gielinkg** [comment]
Updated email thread:


[Re: Query Regarding External Cloud Provider.pdf](https://github.com/urbanbigdatacentre/ideamaps-models/files/15418600/Re.Query.Regarding.External.Cloud.Provider.pdf)

**Comment by andymithamclarke** [comment]
🚀

**Comment by gielinkg** [comment]
We are closing this issue and creating a new one for the update of the ethics application, which satisfies the criteria in this issue regarding compliance with uni policies. I am now liaising with Procurement and Yevdokia about how to setup these services properly. I will update on this in the payment issue #39

**Comment by andymithamclarke** [comment]
[like]  Andrew Clarke reacted to your message:
________________________________
