### ISSUE TITLE
Update DPIA document on the ethics application

### ISSUE THREAD

**Issue by gielinkg** [urbanbigdatacentre/ideamaps-models#41]
We need to update the DPIA in the ethics application to reflect the use of Nhost as a new cloud provider. 

We will update the following sections: 

Once this is updated, we pass to JPA for review and submission to the ethics board. This issue can be closed when the updates are submitted to the ethics board.

**Comment by andymithamclarke** [comment]
Need to change 2 documents:

- Azure to -> UofG approved provider.

@gielinkg to get in touch with Nhost with UofG

**Comment by diegopajarito** [comment]
Closing this issue after updating two documents:

- DMP 
- DPIA

The changes were in sections that referred to the use of Azure Cloud services to store research data. They now refer to cloud providers approved by the UofG as a generic reference that covers either Azure or others like AWS or Nhost. 

These documents are ready to be submitted to the ethics board by @joaoporto
