### ISSUE TITLE
Review Reusability Document

### ISSUE THREAD

**Issue by andymithamclarke** [urbanbigdatacentre/ideamaps-models#43]
@Gtregon to provide comments and feedback on the Reusability document created by @Adenikemie and @AlexandraMiddleton .

This issue can be closed once these comments are in the document and a link has been shared in this issue.

**Comment by gielinkg** [comment]
@Gtregon - update here please

**Comment by Gtregon** [comment]
✅ Definition of Done

- [ ] 1. Define acceptance criteria.
- [ ] 2. Assess the need for a review process. If a review process is required, the issue states:
      i. Who is involved in the review?
      ii. When will the review take place?
      iii. Who is responsible for taking on the feedback?
      iv. What additional tasks are involved and are they visible on the backlog?
- [ ]  3. Make progress and post updates.
- [ ]  4. Check off completed acceptance criteria.
- [ ]  5. Post links to digital outputs.
- [ ]  6. Note the value added to the product.

**Comment by Gtregon** [comment]
✅ Definition of Done

- [x] 1. Define acceptance criteria.
The document includes a set of instructions for using validation data to validate model outputs and produce new potential reference data. The document allows future modellers to repeat the process and also paves the way for automating these processes in the near future (phase 2.2.)
- [x] 2. Assess the need for a review process. If a review process is required, the issue states:
      i. Who is involved in the review? @Gtregon 
      ii. When will the review take place? Review has been conducted remotely and the word document was reviewed
      iii. Who is responsible for taking on the feedback? @Adenikemie @AlexandraMiddleton 
      iv. What additional tasks are involved and are they visible on the backlog? NA
- [ ]  3. Make progress and post updates. NA
- [x]  4. Check off completed acceptance criteria.
- [x]  5. Post links to digital outputs.
New version: https://gla-my.sharepoint.com/:w:/g/personal/grant_tregonning_glasgow_ac_uk/ESVayaVD8fFAlkRAKZ3t-3UBjdtIm2j-GCXr4AGnmZU_QA?e=uhinBP
Old version: https://gla-my.sharepoint.com/:w:/g/personal/grant_tregonning_glasgow_ac_uk/EZkpaWmGS01Pny8G9HGeE8EBsdlNia2bUplkDfT5dJNG_Q?e=3F911O
- [x]  6. Note the value added to the product.
The document will provide future modellers with instructions for using validation data from PAR sessions to validate model outputs, produce confidence scores for the interface and produce new reference data.
