### ISSUE TITLE
2 Page Model Brief Draft for Healthcare Model

### ISSUE THREAD

**Issue by andymithamclarke** [urbanbigdatacentre/ideamaps-models#46]
### ✅ Definition of Done
---

- [ ] 1. Define acceptance criteria.
- [ ] 2. Assess the need for a review process. If a review process is required, the issue states:
    1. Who is involved in the review?
    2. When will the review take place?
    3. Who is responsible for taking on the feedback?
    4. What additional tasks are involved and are they visible on the backlog?
- [ ] 3. Make progress and post updates.
- [ ] 4. Check off completed acceptance criteria.
- [ ] 5. Post links to digital outputs.
- [ ] 6. Note the value added to the product.

**Comment by andymithamclarke** [comment]
We need to create a document with the following information:

- Inputs 
- Outputs
- Modelling Approach
- Overview
- References

In order to get to this point - different modelling approaches should be compared.

This issue can be closed once the document first draft has been created and posted and a review process has been described here.

**Comment by gielinkg** [comment]
This task includes: 
- Proposing a technical approach for the model; defining a set of categories. 
- Reviewing the datasets used for the model

**Comment by diegopajarito** [comment]
We have received replies from Qunshan and Sabitu. Two new references about health care accessibility in Nairobi have been added. There is also an expression of interest to get more data from Kano from our local partners. 

The 2 page doc will follow the structure of previous model definitions with the sections described in previous comments.
Inputs
Outputs
Modelling Approach
Overview
References
* Proposing a technical approach for the model; defining a set of categories.
* Reviewing the datasets used for the model

The draft document will be available here https://docs.google.com/document/d/1lBspWLuTfyq56bfxzOGfa-DfSrFFIYml/edit?usp=sharing&ouid=115390532617165323330&rtpof=true&sd=true

**Comment by diegopajarito** [comment]
Model brief document updated with the structure and initial contents for sections (intro, data, modelling approach, study area). Other sections are still to be updated.

**Comment by gielinkg** [comment]
@diegopajarito  completed the draft, and is going to circulate with the rest of team. Next steps will be mapped in Sprint 2.
