### ISSUE TITLE
Create Model Spec for Morphological Informality

### ISSUE THREAD

**Issue by andymithamclarke** [urbanbigdatacentre/ideamaps-models#5]
We need to produce a 1 - 2 page document about the morphological informality model to present at the full team meeting for around 30 minutes.

In this document we need to detail the following elements:
- Definitions from Monika with examples
- Compare this to previous descriptions
- What does this mean in each city

This is not a technical summary. 

This issue can be closed with a link posted in this thread to the document.

**Comment by Gtregon** [comment]
The first draft of the document has been complete. Link [here](https://docs.google.com/document/d/1bdfbZNTN81466KOmfxCcl4H-2TxtH2ow/edit)
