### ISSUE TITLE
Full Technical Model Documentation

### ISSUE THREAD

**Issue by andymithamclarke** [urbanbigdatacentre/ideamaps-models#52]

**Comment by gielinkg** [comment]
Produce a document that outlines/describes the architecture for the model, which includes: 
- Data Inputs [covariates]
- Reference Data
- Model source code
- Layperson's documentation
- Technical Specification
- A Read Me file and Github link

**Comment by gielinkg** [comment]
@Gtregon testing the full model documentation, reference data, source code, and specs/documentation.

**Comment by Gtregon** [comment]
Closing issue as all items have been moved to their relevant destinations i.e. GDrive, Git, CRIB. This will be tested during the workshop on Tuesday 20th and feedback/improvements will be made by Friday 23rd August. See PDF below with links to the three repositories.

[IDEAMAPS Handover Workshop Agenda.pdf](https://github.com/user-attachments/files/16662735/IDEAMAPS.Handover.Workshop.Agenda.pdf)
