### ISSUE TITLE
Handover Documentation

### ISSUE THREAD

**Issue by andymithamclarke** [urbanbigdatacentre/ideamaps-models#53]
@Gtregon @diegopajarito to define this task with @qszhao

**Comment by gielinkg** [comment]
- [ ] - Review WP2/3 folder structure
- [ ] - Establish access to documents/agree to same folder structure (for Diego)
- [ ] - Uploading models and for development scripts to Github
- [ ] - Masters students: integrate new masters students into the handover process -- bringing them up to speed with what we're doing @diegopajarito @Gtregon

**Comment by gielinkg** [comment]
@Gtregon and @diegopajarito: Highlighting here that we need to discuss the transition of convening tasks for the Modelling Community of Practice. 

The CoP is one of the main ways that we invite people to get involved when they reach out to the Network and it is advertised in our web pages. If we expect a pause in CoP activities, it's good to make this visible.

**Comment by qszhao** [comment]
Thanks all for the heads up. Here are a couple of suggestions from my side: 
1. CoP: I agree we should find an interim contact. If we cannot find it before our new PDRA starts, then we will need to pause it for some time. 
2. I think there is a general request from the WP2/3 to upload the model input data and outputs into crib. If we aim to do it via GitHub then I think it is fine. Would it be a private repo then we can invite all the colleagues?  We just need to bare in mind that GitHub cannot host large datasets. 
3. Documentation will be very important for our models, so I will try to go over it with @gielinkg next month.

**Comment by Gtregon** [comment]
I am closing this issue as I have created smaller sub issues for each task.
