### ISSUE TITLE
Transform All City Outputs for Ingestion

### ISSUE THREAD

**Issue by gielinkg** [urbanbigdatacentre/ideamaps-models#55]
Please define this task - any code used should be uploaded to Github.

**Comment by gielinkg** [comment]
Acceptance criteria: 
Model outputs are formatted and ready to be ingested 

Following these requirements for the platform: 
https://github.com/urbanbigdatacentre/ideamaps-application-backend/blob/development/docs/data/model-outputs.md

**Comment by Gtregon** [comment]
Outputs have been transformed. @Gtregon will work on refining the lat/lon coords so that the projections align with the platform. @andymithamclarke and @Gtregon will regroup this week to finalise the ingestion process.

**Comment by andymithamclarke** [comment]
Closing this as complete @Gtregon - is there any additional resources that require upload to the repo? E.g Transformation script updates?
