### ISSUE TITLE
Draft layperson's document for Healthcare Model

### ISSUE THREAD

**Issue by gielinkg** [urbanbigdatacentre/ideamaps-models#57]

**Comment by andymithamclarke** [comment]
Reference a definition of:

1. Healthcare 
2. Accessibility

**Comment by andymithamclarke** [comment]
How will validation work for this model?

How will the thresholds for Low - Medium - High - work for this model?

**Comment by diegopajarito** [comment]
The draft has been prepared and initially validated with Taiwo and Sabitu 

A version is available here https://gla-my.sharepoint.com/:p:/g/personal/diego_pajaritograjales_glasgow_ac_uk/EU5eC4obdJVPrEad5tC-XToBrB2WO_GIARIXxiq8-uTyyw?e=f5cQwt


![Image](https://github.com/user-attachments/assets/4d5113b0-f4cf-4ce8-aeaf-5d7444d8b540)
