### ISSUE TITLE
Draft of the Technical Specification for the Healthcare Model

### ISSUE THREAD

**Issue by gielinkg** [urbanbigdatacentre/ideamaps-models#58]
This issue will end when a draft of the technical specification for accessibility to health care is shared with the domain expert group. 

The document will have three main sections
- Data coming from #73 
- A description of the two approaches available
- A definition for accessibility from #76 

This document will be validated in two sessions with the domain experts from Nigeria and Kenya

**Comment by diegopajarito** [comment]
The draft will include at least the following elements

- Data gathered (Road Network, Health Care Facilities, Grid)
- The alternatives we are considering (HeiGIT & PySAL library)
- Definition of Accessibility adopted
- Outputs structure (three models)

**Comment by andymithamclarke** [comment]
Reference a definition of:

1. Healthcare 
2. Accessibility

**Comment by diegopajarito** [comment]
Document with the draft of our technical specification is available here https://docs.google.com/document/d/1lBspWLuTfyq56bfxzOGfa-DfSrFFIYml/edit?usp=sharing&ouid=115390532617165323330&rtpof=true&sd=true

**Comment by andymithamclarke** [comment]
This document should include clarity about whether we will run the model in Kano AND Lagos. - and information about any addiotional work thats incvoled in doing so

**Comment by diegopajarito** [comment]
After the meeting on Monday with Taiwo, the team will finalise the 

We have confirmed the general workflow is approved
The team has requested an unlimited API / higher limits to HeiGIT to be prepared for processing more data.  
Extending the end date to 17 Sep Tuesday

**Comment by diegopajarito** [comment]
Outstanding tasks. 
- Definition of the thresholds for Low/Med/High
- Description: transforming isochrone polygons into our grid

**Comment by andymithamclarke** [comment]
See #60
