### ISSUE TITLE
Document Ingestion Pipeline

### ISSUE THREAD

**Issue by andymithamclarke** [urbanbigdatacentre/ideamaps-models#6]
We need to create a document that describes the process of ingesting data from the model repo to the platform.

This document needs to detail the following elements:
- Data formats for outputs
- Hasura endpoints and requirements
- Links to the schema 
- How to use the Action
- Quality Control processes
- Error and response codes - with messages

...

This issue can be closed once the document has been created and uploaded to the /models repo within it's own isolated space.

**Comment by andymithamclarke** [comment]
This should also include the data management side of things.

Serkan suggests that we may not want to keep old models - a clean up process. We should document this as part of the document.

**Comment by andymithamclarke** [comment]
Reccomendation from Serkan - should we not be storing our data on Github - we should be using a data repository to store these files instead.

**Comment by diegopajarito** [comment]
Data storage in GitHub is to be defined.

The initial version of the documentation is defined. Closing this issue to start a new one for specific details on the technical design.
