### ISSUE TITLE
Approval of Technical Specification Document - HEALTHCARE

### ISSUE THREAD

**Issue by gielinkg** [urbanbigdatacentre/ideamaps-models#60]
@diegopajarito  to define how we get to this approval stage. This task is necessary to move forward with running of a crude model. 

The approval and review processes should also be documented so that we can understand how we reached the decisions on the development of the new model. (who took part? what were the main steps?)

**Comment by diegopajarito** [comment]
Added dates.

The approval depends on the generation of sections
Data #73 
Methods #58 
Definition of accessibility #76

**Comment by andymithamclarke** [comment]
This issue can be closed with 
1. the approval from Qunshan
2. a review from the WP2/3 team 
3. A final approval from Joao.

**Comment by andymithamclarke** [comment]
@diegopajarito needs to prepare maps showing the different input datasets. Then we need to hold a review meeting with Nigerian team to check these for appropriate usage.

These maps will show the distribution of the data that the model will use to create its outputs.

**Comment by diegopajarito** [comment]
Approval gained from Taiwo and Sabitu on 16 Sep

**Comment by diegopajarito** [comment]
We got no objections and approval from the WP2/3 team on 19 Sept in the WP meeting. 
We have the final approval from João pending on the final version of the model Spec
