### ISSUE TITLE
Running of the Kano + Lagos morphological informality model

### ISSUE THREAD

**Issue by gielinkg** [urbanbigdatacentre/ideamaps-models#63]
### ✅ Definition of Done
---

- [ ] 1. Define acceptance criteria.
- [ ] 2. Assess the need for a review process. If a review process is required, the issue states:
    1. Who is involved in the review?
    2. When will the review take place?
    3. Who is responsible for taking on the feedback?
    4. What additional tasks are involved and are they visible on the backlog?
- [ ] 3. Make progress and post updates.
- [ ] 4. Check off completed acceptance criteria.
- [ ] 5. Post links to digital outputs.
- [ ] 6. Note the value added to the product.

**Comment by gielinkg** [comment]
The model developed in issue #54 will be used to run the Kano and Lagos model this week. @Gtregon has streamlined the script so that model outputs are generated faster.

**Comment by Gtregon** [comment]
Model has been run for Kano and Lagos. Outputs have been generated in a .csv and gpkg file. @Gtregon will start the pipeline process to feed this into the platform and will work with WP1 to do this.
