### ISSUE TITLE
Review WP2/3 folder structure

### ISSUE THREAD

**Issue by Gtregon** [urbanbigdatacentre/ideamaps-models#68]
Folder structure within GDrive and Github has been refined. CRIB folder structure has been reviewed but has not yet been transferred to the public drive on the server as Serkan is still on AL and we are unable to create folders within this drive. Grant will transfer the folder structure once Serkan has granted access.

This issue can be closed when there is a folder structure created for GDrive, Github and CRIB

### ✅ Definition of Done
---

- [ ] 1. Define acceptance criteria.
- [ ] 2. Assess the need for a review process. If a review process is required, the issue states:
    1. Who is involved in the review?
    2. When will the review take place?
    3. Who is responsible for taking on the feedback?
    4. What additional tasks are involved and are they visible on the backlog?
- [ ] 3. Make progress and post updates.
- [ ] 4. Check off completed acceptance criteria.
- [ ] 5. Post links to digital outputs.
- [ ] 6. Note the value added to the product.

**Comment by gielinkg** [comment]
Waiting for Serkan to give access to the public folders in CRIB.

**Comment by Gtregon** [comment]
Complete. Folder structure listed in workshop #74  agenda below.


[IDEAMAPS Handover Workshop Agenda.pdf](https://github.com/user-attachments/files/16662758/IDEAMAPS.Handover.Workshop.Agenda.pdf)

**Comment by Gtregon** [comment]
Complete. Folder structure listed in workshop #74  agenda below.


[IDEAMAPS Handover Workshop Agenda.pdf](https://github.com/user-attachments/files/16662758/IDEAMAPS.Handover.Workshop.Agenda.pdf)
