### ISSUE TITLE
Review handover process with RA's (Handover Workshop)

### ISSUE THREAD

**Issue by Gtregon** [urbanbigdatacentre/ideamaps-models#70]
@Gtregon will run a handover workshop with @diegopajarito @Adenikemie, Manuella and Xingyi to test existing folder structures, access to datasets, source code, documentation etc to ensure that there are no gaps in information and that future modellers (Research assistants and external modelling community) can repeat our process and integrate their outputs within the ecosystem.

This exercise will mainly cover the contents of #52 

### ✅ Definition of Done
---

- [ ] 1. Define acceptance criteria.
- [ ] 2. Assess the need for a review process. If a review process is required, the issue states:
    1. Who is involved in the review?
    2. When will the review take place?
    3. Who is responsible for taking on the feedback?
    4. What additional tasks are involved and are they visible on the backlog?
- [ ] 3. Make progress and post updates.
- [ ] 4. Check off completed acceptance criteria.
- [ ] 5. Post links to digital outputs.
- [ ] 6. Note the value added to the product.

**Comment by gielinkg** [comment]
@Gtregon  to invite @diegopajarito and Sebastian

**Comment by gielinkg** [comment]
@Gtregon to invite @diegopajarito and Sebastian

**Comment by gielinkg** [comment]
Full documentation should be completed by the time this workshop is run, and the information will be trialed and tested by participants.

**Comment by Gtregon** [comment]
handover workshop complete. See below for agenda. This has been forwarded to the WP2/3 team so that they have a copy of it. The workshop was attended by @diegopajarito @Adenikemie @AlexandraMiddleton @Xingyi-cici @manuellacomerio Monika and Sebastian.

[IDEAMAPS Handover Workshop Agenda.pdf](https://github.com/user-attachments/files/16760812/IDEAMAPS.Handover.Workshop.Agenda.pdf)
