### ISSUE TITLE
All data about health care is prepared and available on CRIB

### ISSUE THREAD

**Issue by gielinkg** [urbanbigdatacentre/ideamaps-models#73]
### ✅ Definition of Done
---

- [x] 1. Define acceptance criteria.
- [ ] 2. Assess the need for a review process. If a review process is required, the issue states:
    1. Who is involved in the review?
    2. When will the review take place?
    3. Who is responsible for taking on the feedback?
    4. What additional tasks are involved and are they visible on the backlog?
- [ ] 3. Make progress and post updates.
- [x] 4. Check off completed acceptance criteria.
- [x] 5. Post links to digital outputs.
- [x] 6. Note the value added to the product.

**Comment by gielinkg** [comment]
Gather data required for the model (road network, health care facilities, output grid) and make it available on CRIB.

**Comment by diegopajarito** [comment]
The title was updated to enclose all data preparation tasks. Dates were set as well.

The following list will serve to check the three datasets to be prepared 
- [ ] Kano's road network data in the latest version available on CRIB
- [ ] Kano's health care facilities data is available on CRIB
- [ ] Kano's output grid is available on CRIB

The data section on issue #42 is also removed.

**Comment by diegopajarito** [comment]
@Xingyi-cici and Diego have uploaded the data about health care to CRIB. Also, we left a copy of it in GDRIVE

The description of the datasets compiled is here https://www.notion.so/Health-Care-Model-a40bed953ab147efb319859bbf6e611c?pvs=4

Three datasets are being considered for the modelling tasks. [GRID 3](https://data.grid3.org/datasets/1b358b47e41244cbaaccb640d9a4bfc9_0/about), [Federal Ministry of Health]([https://www.hfr.health.gov.ng/facilities/hospitals-search?_token=JH99eAZCR3Ynov5QvvbZOf1vi3OvbZ3bmuYDvgAz&state_id=119&lga_id=&ward_id=0&facility_level_id=0&ownership_id=0&operational_status_id=1&registration_status_id=0&license_status_id=0&geo_codes=0&service_type=0&service_category_id=0&facility_name=&entries_per_page=20#](https://www.hfr.health.gov.ng/facilities/hospitals-search?_token=JH99eAZCR3Ynov5QvvbZOf1vi3OvbZ3bmuYDvgAz&state_id=119&lga_id=&ward_id=0&facility_level_id=0&ownership_id=0&operational_status_id=1&registration_status_id=0&license_status_id=0&geo_codes=0&service_type=0&service_category_id=0&facility_name=&entries_per_page=20)) and [OSM](https://apps.heigit.org/healthcare_access/#/method)

Study Area was already stored in CRIB, and we found it under the folder /shared/IDEAMAPS/grids/temp/

For the Road Network, we decided not to upload it to CRIB. We will use the open routing service API to estimate Isochrones. 

The added value is in the three alternatives for locations of healthcare facilities across Kano. This will inform the modelling process and support the decisions we should make.
