### ISSUE TITLE
Review and Discuss the Plan for Survey Tool

### ISSUE THREAD

**Issue by gielinkg** [urbanbigdatacentre/ideamaps-models#75]
### ✅ Definition of Done
---

- [ ] 1. Define acceptance criteria.
- [ ] 2. Assess the need for a review process. If a review process is required, the issue states:
    1. Who is involved in the review?
    2. When will the review take place?
    3. Who is responsible for taking on the feedback?
    4. What additional tasks are involved and are they visible on the backlog?
- [ ] 3. Make progress and post updates.
- [ ] 4. Check off completed acceptance criteria.
- [ ] 5. Post links to digital outputs.
- [ ] 6. Note the value added to the product.

**Comment by andymithamclarke** [comment]
Review meeting took place - team decided that a self hosted version of the Kobotoolbox software is preferrable in the long run.

In the short term if WP4/5 require a tool to use - Kobotoolbox Cloud can be offered. No personal data.

We need to validate this with the WP4/5 team. 

Exact dates of progress with self-hosted version tbc but issues are present within the product backlog.

@diegopajarito @gielinkg are we agreed here / any other comments?
