### ISSUE TITLE
Define accessibility to health care within the IDEAMAPS framework

### ISSUE THREAD

**Issue by diegopajarito** [urbanbigdatacentre/ideamaps-models#76]
This issue will finish when a definition of accessibility to health care is added to the technical specification as a section.
The definition should be aligned with the literature reviewed and the definition for the three levels set for the model outputs. 

The definition will be made by @diegopajarito Xingyi to be presented at the review session.

### ✅ Definition of Done
---

- [ ] 1. Define acceptance criteria.
- [ ] 2. Assess the need for a review process. If a review process is required, the issue states:
    1. Who is involved in the review?
    2. When will the review take place?
    3. Who is responsible for taking on the feedback?
    4. What additional tasks are involved and are they visible on the backlog?
- [ ] 3. Make progress and post updates.
- [ ] 4. Check off completed acceptance criteria.
- [ ] 5. Post links to digital outputs.
- [ ] 6. Note the value added to the product.

**Comment by gielinkg** [comment]
Up for review at Full Team Meeting 28th August
