### ISSUE TITLE
Create Source Code to Produce Healthcare Model Outputs

### ISSUE THREAD

**Issue by andymithamclarke** [urbanbigdatacentre/ideamaps-models#78]
### ✅ Definition of Done
---

- [ ] 1. Define acceptance criteria.
- [ ] 2. Assess the need for a review process. If a review process is required, the issue states:
    1. Who is involved in the review?
    2. When will the review take place?
    3. Who is responsible for taking on the feedback?
    4. What additional tasks are involved and are they visible on the backlog?
- [ ] 3. Make progress and post updates.
- [ ] 4. Check off completed acceptance criteria.
- [ ] 5. Post links to digital outputs.
- [ ] 6. Note the value added to the product.

**Comment by andymithamclarke** [comment]
@diegopajarito to set up development environment and write the notebook.

@Xingyi-cici to begin writing the notebook in CRIB.

**Comment by andymithamclarke** [comment]
Closing as complete - @diegopajarito can you post a link to the files and to the commit that was made here please.

**Comment by diegopajarito** [comment]
Link to the model outputs folder https://github.com/urbanbigdatacentre/ideamaps-models/tree/main/Sub-domains/Healthcare/BarriersHealthCareAccess/Kano_v1

Link to the commit https://github.com/urbanbigdatacentre/ideamaps-models/pull/108
