### ISSUE TITLE
Review Healthcare Model Outputs with Internal Stakeholders

### ISSUE THREAD

**Issue by andymithamclarke** [urbanbigdatacentre/ideamaps-models#80]
### ✅ Definition of Done
---

- [ ] 1. Define acceptance criteria.
- [ ] 2. Assess the need for a review process. If a review process is required, the issue states:
    1. Who is involved in the review?
    2. When will the review take place?
    3. Who is responsible for taking on the feedback?
    4. What additional tasks are involved and are they visible on the backlog?
- [ ] 3. Make progress and post updates.
- [ ] 4. Check off completed acceptance criteria.
- [ ] 5. Post links to digital outputs.
- [ ] 6. Note the value added to the product.

**Comment by diegopajarito** [comment]
We have prepared new model outputs (isochrones) considering only public HC facilities. These outputs will be revised with domain experts.

**Comment by gielinkg** [comment]
Healthcare model outputs were put forward at a full team meeting and follow up meetings with Sabitu and Taiwo. Helen and Joao have spoken separately about it and questions have been developed collaboratively for the PAR sessions that are focused on the Healthcare model in Kano. The questions are focused on determining the direction for model improvement.
