### ISSUE TITLE
Create Platform Release Pack

### ISSUE THREAD

**Issue by gielinkg** [urbanbigdatacentre/ideamaps-models#83]
### ✅ Definition of Done
---

- [ ] 1. Define acceptance criteria.
- [ ] 2. Assess the need for a review process. If a review process is required, the issue states:
    1. Who is involved in the review?
    2. When will the review take place?
    3. Who is responsible for taking on the feedback?
    4. What additional tasks are involved and are they visible on the backlog?
- [ ] 3. Make progress and post updates.
- [ ] 4. Check off completed acceptance criteria.
- [ ] 5. Post links to digital outputs.
- [ ] 6. Note the value added to the product.

**Comment by gielinkg** [comment]
Grace will give Joao release pack in a different format.

**Comment by andymithamclarke** [comment]
Closing as complete - Release pack not scheduled for publication in Cairo - to be returned to post WUF.

@gielinkg let me know if you agree
