### ISSUE TITLE
Press Release for Platform

### ISSUE THREAD

**Issue by gielinkg** [urbanbigdatacentre/ideamaps-models#87]
### ✅ Definition of Done
---

- [ ] 1. Define acceptance criteria.
- [ ] 2. Assess the need for a review process. If a review process is required, the issue states:
    1. Who is involved in the review?
    2. When will the review take place?
    3. Who is responsible for taking on the feedback?
    4. What additional tasks are involved and are they visible on the backlog?
- [ ] 3. Make progress and post updates.
- [ ] 4. Check off completed acceptance criteria.
- [ ] 5. Post links to digital outputs.
- [ ] 6. Note the value added to the product.

**Comment by gielinkg** [comment]
Grace + Martin

**Comment by gielinkg** [comment]
Martin sent a draft press release to @joaoporto on 21/10 -- need to have this reviewed ASAP so that Martin can share with external relations for release on Nov. 5th.

**Comment by gielinkg** [comment]
Joao said we should not release this urgently, if it's not ready, then we should wait.

**Comment by gielinkg** [comment]
Grace ask Martin for edit access.

**Comment by andymithamclarke** [comment]
I think this is complete @gielinkg ?

**Comment by andymithamclarke** [comment]
Press release created and disseminated. @gielinkg do you have some additional details + link here? Feel free to close :)

**Comment by andymithamclarke** [comment]
Closing as archived - work complete
