### ISSUE TITLE
Document morphometric indicators

### ISSUE THREAD

**Issue by manuellacomerio** [urbanbigdatacentre/ideamaps-models#89]
@SebastianHafner has received the notebooks and data from Angela and Pengyu and we're going to try to reproduce building morphometrics (SDS and ISL) to check for reproducibility and replicability.

Strategy to replicate traceability chain morphological subdomains:

1. Define small test area in Nairobi
2. Use Pengyu’s code to run L0 to L3 for test area
  a. Check for reproducibility
  b. Check for replicability (use Angela’s input data to verify)
3. Use Angela’s code to run L4 to L7 for test area
  a. Check for reproducibility
  b. Check for replicability (use Grant’s input data to verify)

**Comment by diegopajarito** [comment]
@SebastianHafner @diegopajarito to discuss the way to share feedback data coming out of the platform (private/public) across the team

**Comment by andymithamclarke** [comment]
Closing as archive - work captured in #137
