### ISSUE TITLE
Re-run code for RF, GB and AB models

### ISSUE THREAD

**Issue by manuellacomerio** [urbanbigdatacentre/ideamaps-models#90]

**Comment by diegopajarito** [comment]
The models have been run for RF, GB, AB. 
This has produced two CSV files per model, according to Grant's model approach. 
These represent model outputs for Nairobi

**Comment by diegopajarito** [comment]
Closed as complete
A question remains about the follow-up tasks regarding the use of those outputs. Paper? Platform-WUF?
