### ISSUE TITLE
Review of the Morphological Informality Approach

### ISSUE THREAD

**Issue by andymithamclarke** [urbanbigdatacentre/ideamaps-models#93]
This is a process of reviewing and agreeing the technical specification of the Morphological Informality document.

The key reviewers are:

- Monika
- Dana
- Ryan
- Qunshan 

They need to review both the OUTPUTS and APPROACH. This could generate additional backlog tasks depending on the need to recalculate the model outputs.

@diegopajarito to own this facilitation. If ALL of the above reviewers are not there - DO NOT do the review.

If ALL of the reviewers agree that changes are required AND agree on what those changes are - we need to create and action plan regarding those changes.

If the tasks are minor and can be completed by @manuellacomerio and @qszhao - then we will schedule them in this sprint.

If they are not - they must be delayed until Sebastian has arrived.

### ✅ Definition of Done
---

- [ ] 1. Define acceptance criteria.
- [ ] 2. Assess the need for a review process. If a review process is required, the issue states:
    1. Who is involved in the review?
    2. When will the review take place?
    3. Who is responsible for taking on the feedback?
    4. What additional tasks are involved and are they visible on the backlog?
- [ ] 3. Make progress and post updates.
- [ ] 4. Check off completed acceptance criteria.
- [ ] 5. Post links to digital outputs.
- [ ] 6. Note the value added to the product.

**Comment by diegopajarito** [comment]
In a meeting on Friday. Monika, Qunshan, Dana & Ryan discussed the options to proceed with the morphological informality. 
Main issue is the lack of training data or reference data to move from slum/non slum to low/med/high.
There are proposals for three options and @diegopajarito @manuellacomerio will prepare a table that sumarieses these. 
The table will list the existing datasets and the processing tasks needed prior to ingest new model outputs into our platform. 

The meeting on 18 Sep will be used to define the approach.

**Comment by andymithamclarke** [comment]
Closing this as complete - decision made to use Morphological Informality is defined as Irregular Layout + Small Dense Structure + Road Metrics **

This now represents a completely different model that is rule based and re uses the results from Angela's work on the above models with the update of the following categorisation:

Low == Neither ISL or SDS or RD
Medium == One of ISL or SDS and RD 
High == Both

**Comment by andymithamclarke** [comment]
More discussions captured in following issues.
