### ISSUE TITLE
Calculate the isochrones for Kano

### ISSUE THREAD

**Issue by Xingyi-cici** [urbanbigdatacentre/ideamaps-models#98]

**Comment by Xingyi-cici** [comment]
Run the isochrones for entire kano

**Comment by andymithamclarke** [comment]
@Xingyi-cici had conversation with Sabitu - questions posed about the isochrones + how do these translate to a level of accessibility ++ for each grid cell.

@diegopajarito + Sabitu + @Xingyi-cici have a set of criteria for low - medium and high to move forward with.

Now the task involves sending the logic to the API for computation and getting results back. There is an issue with API quotas that should be resolved between @diegopajarito and HEIGIT.

Progress updates to follow.

**Comment by Xingyi-cici** [comment]
Got Isochrones from openrouteservice.
